# Generated by Django 5.2.11 on 2026-03-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='package',
            field=models.IntegerField(help_text='Package in LPA'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('student', 'job')},
        ),
    ]
