# Generated by Django 5.2.11 on 2026-03-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_app', '0003_student_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cgpa',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
    ]
