# Generated by Django 5.2.11 on 2026-03-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_app', '0004_alter_student_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, choices=[('BTECH', 'B.Tech'), ('MBA', 'MBA'), ('MCA', 'MCA'), ('BSC', 'B.Sc'), ('MSC', 'M.Sc')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
