# Generated by Django 5.2.11 on 2026-03-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_app', '0005_student_course_student_mobile_student_skills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
