# Generated by Django 5.2.11 on 2026-03-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_app', '0007_remove_job_company_name_job_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
