# Generated by Django 5.2.11 on 2026-03-05 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms_app', '0008_job_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_name',
        ),
    ]
