# Generated by Django 5.2.11 on 2026-03-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_app', '0009_remove_job_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='eligibility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='mode',
            field=models.CharField(blank=True, choices=[('Onsite', 'Onsite'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=20, null=True),
        ),
    ]
