# Generated by Django 5.2.11 on 2026-03-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_app', '0010_job_eligibility_job_location_job_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
