# Generated by Django 5.2.11 on 2026-03-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_app', '0011_alter_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='mode',
        ),
        migrations.AddField(
            model_name='job',
            name='job_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='eligibility',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
