# Generated by Django 5.2.11 on 2026-03-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_app', '0012_remove_job_mode_job_job_mode_alter_job_eligibility'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='Applied', max_length=20),
        ),
    ]
